version: "3.9"
name: liuxiaobo-dc
services:

  mysql8:
    image: mysql:8
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    volumes:
      - mysql8_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mysql8_data: {}
  redis_data: {}